alias vim="mvim -v"
alias vi="vim"
alias brewu='brew update && brew upgrade'
alias rbbe='bundle exec'
alias rbbu='bundle update'
alias rbbi='bundle install'

# Prettify ripgrep
function rg()
{
   command rg -pC2 "$@" | less -RFX
}

#
# User configuration sourced by interactive shells
#

# Source zim
if [[ -s ${ZDOTDIR:-${HOME}}/.zim/init.zsh ]]; then
  source ${ZDOTDIR:-${HOME}}/.zim/init.zsh
fi
export PATH="/usr/local/sbin:$PATH" # homebrew
export PATH="/usr/local/opt/python/libexec/bin:$PATH" # homebrew python
export EDITOR="vim"

# Load rbenv automatically by appending
# the following to ~/.zshrc:

eval "$(rbenv init -)"
